#!/usr/bin/env bash
# Fetches open SonarCloud issues for this project and renders them as
# Markdown — meant to be piped into the body of a GitHub Issue tagged
# `sonar-snapshot` so Claude (and humans) can read the current state
# without having to paste from the SonarCloud UI.
#
# Requirements: bash, curl, jq.
#
# Env (alle optional ausser dem Token):
#   SONAR_TOKEN      Pflicht. SonarCloud-User-Token.
#   SONAR_PROJECT    default: sebolber_homeassistantprotokollcenter
#   SONAR_ORG        default: sebolber
#   SONAR_HOST       default: https://sonarcloud.io
#   WAIT_FOR_SCAN    "1": warte bis der laufende Scan SUCCESS/FAILED/CANCELED
#                    erreicht, bevor die Issues geholt werden. Wichtig, wenn
#                    das Skript direkt im Anschluss an sonarqube-scan-action
#                    laeuft — die Issue-Indexierung ist asynchron.

set -euo pipefail

: "${SONAR_TOKEN:?SONAR_TOKEN must be set}"
SONAR_PROJECT="${SONAR_PROJECT:-sebolber_homeassistantprotokollcenter}"
SONAR_ORG="${SONAR_ORG:-sebolber}"
SONAR_HOST="${SONAR_HOST:-https://sonarcloud.io}"

curl_api() {
  curl --fail --silent --show-error -u "${SONAR_TOKEN}:" "$@"
}

if [ "${WAIT_FOR_SCAN:-0}" = "1" ]; then
  echo "Polling ${SONAR_HOST}/api/ce/component (max 15 min)..." >&2
  for _ in $(seq 1 90); do
    status_json="$(curl_api "${SONAR_HOST}/api/ce/component?component=${SONAR_PROJECT}")"
    queue_count="$(echo "${status_json}" | jq '.queue | length')"
    current_status="$(echo "${status_json}" | jq -r '.current.status // ""')"
    if [ "${queue_count}" = "0" ] && [[ "${current_status}" =~ ^(SUCCESS|FAILED|CANCELED)$ ]]; then
      echo "Scan status: ${current_status} (queue empty)." >&2
      # Sonars Issue-Reindexierung laeuft async NACH dem Scan-COMPLETE.
      # `api/issues/search` liefert sonst die Findings vom vorherigen
      # Scan-State, was den Snapshot stale aussehen laesst. 90s Puffer
      # ist empirisch genug fuer Projekte unserer Groesse (~10k LoC).
      echo "Reindex-Puffer: warte 90s auf Server-seitige Issue-Aktualisierung." >&2
      sleep 90
      break
    fi
    echo "Scan running (queue=${queue_count}, current=${current_status:-pending}). Sleep 10s..." >&2
    sleep 10
  done
fi

tmp_issues="$(mktemp)"
trap 'rm -f "${tmp_issues}" "${tmp_issues}.next"' EXIT

# Paginate /api/issues/search. SonarCloud caps ps at 500 and p at 20 (max 10000 issues).
page=1
total=0
fetched=0
echo "[]" > "${tmp_issues}"
while :; do
  resp="$(curl_api "${SONAR_HOST}/api/issues/search?componentKeys=${SONAR_PROJECT}&resolved=false&ps=500&p=${page}")"
  total="$(echo "${resp}" | jq '.total')"
  batch="$(echo "${resp}" | jq -c '.issues')"
  batch_size="$(echo "${batch}" | jq 'length')"
  if [ "${batch_size}" = "0" ]; then
    break
  fi
  jq -s '.[0] + .[1]' "${tmp_issues}" <(echo "${batch}") > "${tmp_issues}.next"
  mv "${tmp_issues}.next" "${tmp_issues}"
  fetched=$((fetched + batch_size))
  if [ "${fetched}" -ge "${total}" ]; then
    break
  fi
  page=$((page + 1))
  if [ "${page}" -gt 20 ]; then
    echo "SonarCloud limit reached: only first ${fetched} of ${total} issues retrieved." >&2
    break
  fi
done

ts="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
project_url="${SONAR_HOST}/project/overview?id=${SONAR_PROJECT}"

printf '%s\n' "<!-- Auto-generated by scripts/fetch-sonar-issues.sh. Do not edit by hand. -->"
printf '%s\n\n' "# SonarCloud Issue Snapshot"
printf 'Last refreshed: `%s` (UTC).  \n' "${ts}"
printf 'Project: [`%s`](%s). Open issues: **%s** (retrieved: %s).\n\n' "${SONAR_PROJECT}" "${project_url}" "${total}" "${fetched}"

if [ "${total}" = "0" ]; then
  printf 'No open issues. :tada:\n'
  exit 0
fi

for sev in BLOCKER CRITICAL MAJOR MINOR INFO; do
  count="$(jq --arg s "${sev}" '[.[] | select(.severity == $s)] | length' "${tmp_issues}")"
  if [ "${count}" = "0" ]; then
    continue
  fi
  printf '## %s (%s)\n\n' "${sev}" "${count}"
  files="$(jq -r --arg s "${sev}" '.[] | select(.severity == $s) | .component' "${tmp_issues}" | sort -u)"
  while IFS= read -r component; do
    [ -n "${component}" ] || continue
    path="${component#"${SONAR_PROJECT}":}"
    file_count="$(jq --arg s "${sev}" --arg c "${component}" '[.[] | select(.severity == $s and .component == $c)] | length' "${tmp_issues}")"
    printf '<details>\n'
    printf '<summary><code>%s</code> (%s)</summary>\n\n' "${path}" "${file_count}"
    jq -r \
      --arg s "${sev}" \
      --arg c "${component}" \
      --arg host "${SONAR_HOST}" \
      --arg org "${SONAR_ORG}" \
      --arg proj "${SONAR_PROJECT}" '
      .[] | select(.severity == $s and .component == $c) |
      "- L\(.line // "?") · `\(.rule)` · \(.message | gsub("\n"; " ")) " +
      "([rule](\($host)/organizations/\($org)/rules?open=\(.rule | @uri)&rule_key=\(.rule | @uri)), " +
      "[issue](\($host)/project/issues?id=\($proj)&open=\(.key)&resolved=false))"
    ' "${tmp_issues}" | sort -V
    printf '\n</details>\n\n'
  done <<< "${files}"
done
