// AUTO-GENERATED by scripts/generate-findings-i18n.mjs — DO NOT EDIT
//
// Iter E1: Source of truth fuer Findings-Strings ist
// custom_components/messagehub/translations/*.json. Das Generator-Skript
// laeuft als Pre-Build-Step (npm run prebuild) und schreibt diese Datei.
// Hand-edits werden beim naechsten Build ueberschrieben.
//
// Vertrag siehe ../utils/findings-i18n.ts.


export type Lang = "de" | "en" | "es" | "fr" | "it" | "nl";

export interface CodeStrings {
  title: string;
  description: string;
  help_url: string;
}

export const STRINGS: Record<Lang, Record<string, CodeStrings>> = {
  "de": {
    "DPT_MISMATCH": {
      "title": "Erkannter Datentyp widerspricht Projekt-DPT",
      "description": "Auto-Erkenner liefert {inferred_dpt} aus {samples} Stichproben (Confidence {confidence}). Projekt-DPT ist {project_dpt}. Werte werden moeglicherweise falsch dekodiert — bitte ETS-Projekt pruefen. Hinweis: bei Stellantrieben (DPT 5.001), die nur 0% und 100% senden, kann der Auto-Erkenner faelschlich 1.001 vermuten — in dem Fall den Severity-Override auf 'info' setzen.",
      "help_url": "https://support.knx.org/hc/en-us/articles/115001366044-Group-Addresses-Datapoint-Types"
    },
    "VALUE_OUT_OF_RANGE": {
      "title": "Wert ausserhalb des erlaubten DPT-Bereichs",
      "description": "Wert {value} liegt ausserhalb des fuer DPT {dpt} erlaubten Bereichs [{range_min}, {range_max}]. Wahrscheinlich falscher DPT oder fehlerhafte Sensorik.",
      "help_url": "https://support.knx.org/hc/en-us/articles/115001133744-Datapoint-Type"
    },
    "MULTI_RESPONDER": {
      "title": "Mehrere Aktoren antworten auf gleicher GA",
      "description": "{count} Quellen antworten innerhalb {window_ms} ms: {responding_sources}. Wahrscheinlich mehrere Aktoren mit gesetztem L-Flag — kann beabsichtigt sein bei parallelen Aktoren, sonst ETS-Topologie pruefen.",
      "help_url": "https://knx-blogger.de/knx-flags-einfach-erklaert/"
    },
    "READ_NO_RESPONSE": {
      "title": "GroupValueRead bleibt ohne Antwort",
      "description": "Read um {read_at} hat innerhalb von {timeout_sec} s keine Antwort erhalten. Empfaenger fehlt, ist offline oder das L-Flag ist nicht gesetzt.",
      "help_url": "https://support.knx.org/hc/en-us/articles/360019068120-Groups-Diagnostics"
    },
    "TOGGLE_LOOP": {
      "title": "Schaltschleife auf DPT 1.001",
      "description": "GA wechselt zyklisch zwischen 0 und 1 (Periode {period_ms} ms, {cycles} Wertwechsel). Vermutung: gleiche GA wird sendend und hoerend gleichzeitig genutzt.",
      "help_url": "https://community.openhab.org/t/loops-on-knx-bus/22185"
    },
    "MULTI_TIME_MASTER": {
      "title": "Mehrere Zeit-Master auf gleicher GA",
      "description": "{sources} schreiben gemeinsam auf eine GA mit DPT {clock_dpt}. Doppelte Zeitquellen erzeugen Drift — nur ein Geraet als Time-Master konfigurieren.",
      "help_url": "https://support.knx.org/hc/en-us/articles/115001366044-Group-Addresses-Datapoint-Types"
    },
    "RECONNECT_STORM": {
      "title": "Reconnect-Sturm nach Bus-Stille",
      "description": "Nach einer Stille bis {silence_until} feuerte die Quelle einen Burst: {burst_count} Telegramme im 30-s-Fenster (Schnitt sonst {normal_avg}, Faktor {factor}). Typisch fuer Reconnect-Floods nach Bus-Spannungsausfall.",
      "help_url": "https://github.com/home-assistant/core/issues/69328"
    },
    "SEND_CYCLE_DRIFT": {
      "title": "Sendezyklus deutlich verkuerzt",
      "description": "Median-Δt der letzten Periode {recent_median_dt} s vs. Vergleichszeitraum {baseline_median_dt} s — Verhaeltnis {ratio}. Sendezyklus halbiert; vermutlich Hysterese verstellt oder Sensorik defekt.",
      "help_url": "https://knx-blogger.de/was-ist-auf-deinem-knx-bus-los/"
    },
    "REPEAT_APPROXIMATION": {
      "title": "Vermutete Telegrammwiederholungen",
      "description": "{total_repeats} identische Folge-Telegramme mit Δt < 100 ms ueber {period_days} Tage (~ {repeats_per_day}/Tag). Approximation des Repeat-Bits — bestaetigen via xknx-Tracer (BL-D), wenn verfuegbar.",
      "help_url": "https://knx-user-forum.de/forum/%C3%B6ffentlicher-bereich/knx-eib-forum/1611435-unbest%C3%A4tigte-telegramme-telegrammwiederholung"
    },
    "ORPHAN_GA": {
      "title": "GA in Projekt-Whitelist, aber stumm",
      "description": "Im Auswertezeitraum {period_from} bis {period_to} kein einziges Telegramm gesehen. ETS-Projekt enthaelt diese GA — entweder loeschen oder Empfaenger pruefen.",
      "help_url": "https://support.knx.org/hc/en-us/articles/115001822790-Project-Check"
    },
    "STALE_GA": {
      "title": "GA seit Tagen tot",
      "description": "Letztes Telegramm am {last_seen}, seit {days_silent} Tagen keine weitere Aktivitaet. Sensorik defekt oder Linie unterbrochen?",
      "help_url": "https://support.knx.org/hc/en-us/articles/115001822790-Project-Check"
    },
    "SEND_TO_NOWHERE": {
      "title": "Schalt-Telegramm ohne Status-Echo",
      "description": "Write um {write_at} blieb {status_window_ms} ms ohne Status-Echo auf derselben GA. Aktor moeglicherweise offline, unprogrammiert oder Status liegt auf separater GA (False-Positive moeglich).",
      "help_url": "https://support.knx.org/hc/en-us/articles/360019068120-Groups-Diagnostics"
    },
    "ANALYSIS_DISABLED": {
      "title": "Bus-Analyse ist deaktiviert",
      "description": "Der Bus-Analyse-Toggle ist aus — der Listener schreibt keine Telegramme mehr in die Raw- oder Counter-Tabelle. Alle anderen Findings sind deshalb unterdrueckt, damit dieser Tab keinen falschen 'alles OK'-Eindruck erweckt. Aktiviere den Toggle im KNX-Bus-Analyse-Tab oben rechts, um Telegramme wieder zu erfassen.",
      "help_url": ""
    }
  },
  "en": {
    "DPT_MISMATCH": {
      "title": "Inferred datapoint type contradicts project DPT",
      "description": "Auto-detector inferred {inferred_dpt} from {samples} samples (confidence {confidence}). Project DPT is {project_dpt}. Values may be decoded incorrectly — please verify the ETS project. Note: actuators (DPT 5.001) that only send 0% and 100% can be mis-inferred as 1.001 — set the severity override to 'info' if that matches your case.",
      "help_url": "https://support.knx.org/hc/en-us/articles/115001366044-Group-Addresses-Datapoint-Types"
    },
    "VALUE_OUT_OF_RANGE": {
      "title": "Value outside allowed DPT range",
      "description": "Value {value} is outside the allowed range [{range_min}, {range_max}] for DPT {dpt}. Likely wrong DPT or faulty sensor.",
      "help_url": "https://support.knx.org/hc/en-us/articles/115001133744-Datapoint-Type"
    },
    "MULTI_RESPONDER": {
      "title": "Multiple actuators respond on same group address",
      "description": "{count} sources answered within {window_ms} ms: {responding_sources}. Likely multiple actuators with the L-flag set — may be intentional for parallel actuators, otherwise verify the ETS topology.",
      "help_url": "https://knx-blogger.de/knx-flags-einfach-erklaert/"
    },
    "READ_NO_RESPONSE": {
      "title": "GroupValueRead without response",
      "description": "Read at {read_at} received no response within {timeout_sec} s. Receiver missing, offline, or L-flag not set.",
      "help_url": "https://support.knx.org/hc/en-us/articles/360019068120-Groups-Diagnostics"
    },
    "TOGGLE_LOOP": {
      "title": "Switching loop on DPT 1.001",
      "description": "Group address alternates between 0 and 1 (period {period_ms} ms, {cycles} value changes). Likely the same GA is used both sending and listening.",
      "help_url": "https://community.openhab.org/t/loops-on-knx-bus/22185"
    },
    "MULTI_TIME_MASTER": {
      "title": "Multiple time masters on same group address",
      "description": "{sources} both write to a GA with DPT {clock_dpt}. Duplicate time sources cause drift — configure only one device as time master.",
      "help_url": "https://support.knx.org/hc/en-us/articles/115001366044-Group-Addresses-Datapoint-Types"
    },
    "RECONNECT_STORM": {
      "title": "Reconnect storm after bus silence",
      "description": "After silence until {silence_until} the source produced a burst: {burst_count} telegrams in the 30s window (normal {normal_avg}, factor {factor}). Typical for reconnect floods after bus power loss.",
      "help_url": "https://github.com/home-assistant/core/issues/69328"
    },
    "SEND_CYCLE_DRIFT": {
      "title": "Send cycle significantly shortened",
      "description": "Recent median Δt {recent_median_dt} s vs. baseline {baseline_median_dt} s — ratio {ratio}. Send cycle halved; likely a changed hysteresis or faulty sensor.",
      "help_url": "https://knx-blogger.de/was-ist-auf-deinem-knx-bus-los/"
    },
    "REPEAT_APPROXIMATION": {
      "title": "Suspected telegram repeats",
      "description": "{total_repeats} identical follow-up telegrams with Δt < 100 ms across {period_days} days (~ {repeats_per_day}/day). Approximation of the repeat bit — confirm via xknx tracer (BL-D) when available.",
      "help_url": "https://knx-user-forum.de/forum/%C3%B6ffentlicher-bereich/knx-eib-forum/1611435-unbest%C3%A4tigte-telegramme-telegrammwiederholung"
    },
    "ORPHAN_GA": {
      "title": "GA in project whitelist but silent",
      "description": "No telegrams observed in the period from {period_from} to {period_to}. The ETS project lists this GA — remove it or check the receiver.",
      "help_url": "https://support.knx.org/hc/en-us/articles/115001822790-Project-Check"
    },
    "STALE_GA": {
      "title": "GA gone silent",
      "description": "Last telegram at {last_seen}, no activity for {days_silent} days. Sensor faulty or line interrupted?",
      "help_url": "https://support.knx.org/hc/en-us/articles/115001822790-Project-Check"
    },
    "SEND_TO_NOWHERE": {
      "title": "Switching telegram without status echo",
      "description": "Write at {write_at} received no status echo within {status_window_ms} ms on the same GA. Actuator possibly offline, not programmed, or status lives on a separate GA (false positive possible).",
      "help_url": "https://support.knx.org/hc/en-us/articles/360019068120-Groups-Diagnostics"
    },
    "ANALYSIS_DISABLED": {
      "title": "Bus analysis is disabled",
      "description": "The bus analysis toggle is off — the listener no longer records telegrams to the raw or counter tables. All other findings are suppressed so this tab does not create a false 'all good' impression. Enable the toggle in the KNX bus analysis tab to resume telegram capture.",
      "help_url": ""
    }
  },
  "es": {
    "DPT_MISMATCH": {
      "title": "Tipo de datos detectado contradice el DPT del proyecto",
      "description": "El auto-detector infirio {inferred_dpt} de {samples} muestras (confianza {confidence}). DPT del proyecto: {project_dpt}. Los valores podrian decodificarse incorrectamente — verifica el proyecto ETS. Nota: actuadores (DPT 5.001) que solo envian 0% y 100% pueden inferirse erroneamente como 1.001 — establece el override de severity en 'info' si es ese el caso.",
      "help_url": "https://support.knx.org/hc/en-us/articles/115001366044-Group-Addresses-Datapoint-Types"
    },
    "VALUE_OUT_OF_RANGE": {
      "title": "Valor fuera del rango permitido del DPT",
      "description": "El valor {value} está fuera del rango permitido [{range_min}, {range_max}] para el DPT {dpt}. Probablemente DPT incorrecto o sensor defectuoso.",
      "help_url": "https://support.knx.org/hc/en-us/articles/115001133744-Datapoint-Type"
    },
    "MULTI_RESPONDER": {
      "title": "Múltiples actuadores responden en la misma dirección de grupo",
      "description": "{count} fuentes respondieron en {window_ms} ms: {responding_sources}. Probablemente varios actuadores con el L-flag activo — puede ser intencional para actuadores paralelos, en caso contrario verifica la topología ETS.",
      "help_url": "https://knx-blogger.de/knx-flags-einfach-erklaert/"
    },
    "READ_NO_RESPONSE": {
      "title": "GroupValueRead sin respuesta",
      "description": "Read en {read_at} no recibió respuesta en {timeout_sec} s. Receptor ausente, desconectado o L-flag no configurado.",
      "help_url": "https://support.knx.org/hc/en-us/articles/360019068120-Groups-Diagnostics"
    },
    "TOGGLE_LOOP": {
      "title": "Bucle de conmutación en DPT 1.001",
      "description": "La dirección de grupo alterna entre 0 y 1 (período {period_ms} ms, {cycles} cambios de valor). Probablemente la misma GA se usa para enviar y escuchar simultáneamente.",
      "help_url": "https://community.openhab.org/t/loops-on-knx-bus/22185"
    },
    "MULTI_TIME_MASTER": {
      "title": "Múltiples maestros de tiempo en la misma dirección de grupo",
      "description": "{sources} escriben en una GA con DPT {clock_dpt}. Fuentes de tiempo duplicadas causan deriva — configura solo un dispositivo como maestro de tiempo.",
      "help_url": "https://support.knx.org/hc/en-us/articles/115001366044-Group-Addresses-Datapoint-Types"
    },
    "RECONNECT_STORM": {
      "title": "Tormenta de reconexión tras silencio del bus",
      "description": "Tras silencio hasta {silence_until} la fuente produjo una ráfaga: {burst_count} telegramas en la ventana de 30 s (normal {normal_avg}, factor {factor}). Típico de inundaciones de reconexión tras corte de alimentación.",
      "help_url": "https://github.com/home-assistant/core/issues/69328"
    },
    "SEND_CYCLE_DRIFT": {
      "title": "Ciclo de envío notablemente acortado",
      "description": "Mediana Δt reciente {recent_median_dt} s frente a referencia {baseline_median_dt} s — proporción {ratio}. Ciclo de envío reducido a la mitad; probablemente histeresis modificada o sensor defectuoso.",
      "help_url": "https://knx-blogger.de/was-ist-auf-deinem-knx-bus-los/"
    },
    "REPEAT_APPROXIMATION": {
      "title": "Repeticiones de telegrama supuestas",
      "description": "{total_repeats} telegramas consecutivos idénticos con Δt < 100 ms durante {period_days} días (~ {repeats_per_day}/día). Aproximación del bit de repetición — confirmar mediante el rastreador xknx (BL-D) cuando esté disponible.",
      "help_url": "https://knx-user-forum.de/forum/%C3%B6ffentlicher-bereich/knx-eib-forum/1611435-unbest%C3%A4tigte-telegramme-telegrammwiederholung"
    },
    "ORPHAN_GA": {
      "title": "GA en lista del proyecto pero silenciosa",
      "description": "No se observaron telegramas en el período del {period_from} al {period_to}. El proyecto ETS contiene esta GA — elimínala o verifica el receptor.",
      "help_url": "https://support.knx.org/hc/en-us/articles/115001822790-Project-Check"
    },
    "STALE_GA": {
      "title": "GA en silencio desde hace días",
      "description": "Último telegrama el {last_seen}, sin actividad durante {days_silent} días. ¿Sensor defectuoso o línea interrumpida?",
      "help_url": "https://support.knx.org/hc/en-us/articles/115001822790-Project-Check"
    },
    "SEND_TO_NOWHERE": {
      "title": "Telegrama sin eco de estado",
      "description": "El Write a las {write_at} no recibió eco de estado en {status_window_ms} ms en la misma GA. Actuador posiblemente offline, no programado o el estado vive en una GA separada (posible falso positivo).",
      "help_url": "https://support.knx.org/hc/en-us/articles/360019068120-Groups-Diagnostics"
    },
    "ANALYSIS_DISABLED": {
      "title": "El analisis del bus esta desactivado",
      "description": "El interruptor de analisis del bus esta apagado — el listener ya no registra telegramas en las tablas raw ni counter. Los demas hallazgos estan suprimidos para que esta pestana no de la falsa impresion de 'todo bien'. Activa el interruptor en la pestana de analisis del bus KNX para reanudar la captura de telegramas.",
      "help_url": ""
    }
  },
  "fr": {
    "DPT_MISMATCH": {
      "title": "Type de données détecté contredit le DPT du projet",
      "description": "Le detecteur a infere {inferred_dpt} a partir de {samples} echantillons (confiance {confidence}). DPT du projet: {project_dpt}. Les valeurs sont peut-etre mal decodees — verifie le projet ETS. Note: les actionneurs (DPT 5.001) qui n'envoient que 0% et 100% peuvent etre identifies a tort comme 1.001 — definis l'override de severite sur 'info' si c'est ton cas.",
      "help_url": "https://support.knx.org/hc/en-us/articles/115001366044-Group-Addresses-Datapoint-Types"
    },
    "VALUE_OUT_OF_RANGE": {
      "title": "Valeur hors de la plage autorisée du DPT",
      "description": "La valeur {value} est en dehors de la plage autorisée [{range_min}, {range_max}] pour le DPT {dpt}. Probablement DPT incorrect ou capteur défectueux.",
      "help_url": "https://support.knx.org/hc/en-us/articles/115001133744-Datapoint-Type"
    },
    "MULTI_RESPONDER": {
      "title": "Plusieurs actionneurs répondent sur la même adresse de groupe",
      "description": "{count} sources ont répondu en {window_ms} ms : {responding_sources}. Probablement plusieurs actionneurs avec le L-flag actif — peut être intentionnel pour des actionneurs parallèles, sinon vérifiez la topologie ETS.",
      "help_url": "https://knx-blogger.de/knx-flags-einfach-erklaert/"
    },
    "READ_NO_RESPONSE": {
      "title": "GroupValueRead sans réponse",
      "description": "Le Read à {read_at} n'a reçu aucune réponse en {timeout_sec} s. Récepteur absent, hors ligne ou L-flag non configuré.",
      "help_url": "https://support.knx.org/hc/en-us/articles/360019068120-Groups-Diagnostics"
    },
    "TOGGLE_LOOP": {
      "title": "Boucle de commutation sur DPT 1.001",
      "description": "L'adresse de groupe alterne entre 0 et 1 (période {period_ms} ms, {cycles} changements de valeur). Probablement la même GA est utilisée pour émettre et écouter simultanément.",
      "help_url": "https://community.openhab.org/t/loops-on-knx-bus/22185"
    },
    "MULTI_TIME_MASTER": {
      "title": "Plusieurs maîtres de temps sur la même adresse de groupe",
      "description": "{sources} écrivent ensemble sur une GA avec DPT {clock_dpt}. Sources de temps doubles provoquent une dérive — configurer un seul appareil en tant que maître de temps.",
      "help_url": "https://support.knx.org/hc/en-us/articles/115001366044-Group-Addresses-Datapoint-Types"
    },
    "RECONNECT_STORM": {
      "title": "Tempête de reconnexion après silence du bus",
      "description": "Après un silence jusqu'à {silence_until} la source a généré une rafale : {burst_count} télégrammes dans la fenêtre de 30 s (normal {normal_avg}, facteur {factor}). Typique d'inondations de reconnexion après coupure d'alimentation.",
      "help_url": "https://github.com/home-assistant/core/issues/69328"
    },
    "SEND_CYCLE_DRIFT": {
      "title": "Cycle d'envoi nettement raccourci",
      "description": "Médiane Δt récente {recent_median_dt} s vs. référence {baseline_median_dt} s — ratio {ratio}. Cycle d'envoi divisé par deux ; hystérésis probablement modifiée ou capteur défectueux.",
      "help_url": "https://knx-blogger.de/was-ist-auf-deinem-knx-bus-los/"
    },
    "REPEAT_APPROXIMATION": {
      "title": "Répétitions de télégramme suspectées",
      "description": "{total_repeats} télégrammes consécutifs identiques avec Δt < 100 ms sur {period_days} jours (~ {repeats_per_day}/jour). Approximation du bit de répétition — confirmer via le traceur xknx (BL-D) lorsqu'il est disponible.",
      "help_url": "https://knx-user-forum.de/forum/%C3%B6ffentlicher-bereich/knx-eib-forum/1611435-unbest%C3%A4tigte-telegramme-telegrammwiederholung"
    },
    "ORPHAN_GA": {
      "title": "GA dans la liste du projet mais silencieuse",
      "description": "Aucun télégramme observé entre {period_from} et {period_to}. Le projet ETS contient cette GA — supprimez-la ou vérifiez le récepteur.",
      "help_url": "https://support.knx.org/hc/en-us/articles/115001822790-Project-Check"
    },
    "STALE_GA": {
      "title": "GA silencieuse depuis plusieurs jours",
      "description": "Dernier télégramme le {last_seen}, aucune activité depuis {days_silent} jours. Capteur défectueux ou ligne interrompue ?",
      "help_url": "https://support.knx.org/hc/en-us/articles/115001822790-Project-Check"
    },
    "SEND_TO_NOWHERE": {
      "title": "Télégramme sans écho de statut",
      "description": "Le Write à {write_at} n'a reçu aucun écho de statut dans {status_window_ms} ms sur la même GA. Actionneur peut-être hors ligne, non programmé ou statut sur une GA séparée (faux positif possible).",
      "help_url": "https://support.knx.org/hc/en-us/articles/360019068120-Groups-Diagnostics"
    },
    "ANALYSIS_DISABLED": {
      "title": "L'analyse du bus est desactivee",
      "description": "Le bouton d'analyse du bus est desactive — le listener n'enregistre plus de telegrammes dans les tables raw ou counter. Tous les autres findings sont supprimes afin que cet onglet ne donne pas une fausse impression de 'tout va bien'. Activez le bouton dans l'onglet d'analyse du bus KNX pour reprendre la capture des telegrammes.",
      "help_url": ""
    }
  },
  "it": {
    "DPT_MISMATCH": {
      "title": "Tipo di dato rilevato contraddice il DPT del progetto",
      "description": "Il rilevatore automatico ha inferito {inferred_dpt} da {samples} campioni (confidenza {confidence}). DPT progetto: {project_dpt}. I valori potrebbero essere decodificati in modo errato — verifica il progetto ETS. Nota: gli attuatori (DPT 5.001) che inviano solo 0% e 100% possono essere erroneamente identificati come 1.001 — imposta l'override di severita su 'info' se e questo il caso.",
      "help_url": "https://support.knx.org/hc/en-us/articles/115001366044-Group-Addresses-Datapoint-Types"
    },
    "VALUE_OUT_OF_RANGE": {
      "title": "Valore fuori dall'intervallo consentito del DPT",
      "description": "Il valore {value} è fuori dall'intervallo consentito [{range_min}, {range_max}] per il DPT {dpt}. Probabilmente DPT errato o sensore difettoso.",
      "help_url": "https://support.knx.org/hc/en-us/articles/115001133744-Datapoint-Type"
    },
    "MULTI_RESPONDER": {
      "title": "Più attuatori rispondono sullo stesso indirizzo di gruppo",
      "description": "{count} sorgenti hanno risposto in {window_ms} ms: {responding_sources}. Probabilmente più attuatori con L-flag impostato — può essere intenzionale per attuatori paralleli, altrimenti verifica la topologia ETS.",
      "help_url": "https://knx-blogger.de/knx-flags-einfach-erklaert/"
    },
    "READ_NO_RESPONSE": {
      "title": "GroupValueRead senza risposta",
      "description": "Read a {read_at} non ha ricevuto risposta entro {timeout_sec} s. Ricevitore assente, offline o L-flag non impostato.",
      "help_url": "https://support.knx.org/hc/en-us/articles/360019068120-Groups-Diagnostics"
    },
    "TOGGLE_LOOP": {
      "title": "Anello di commutazione su DPT 1.001",
      "description": "L'indirizzo di gruppo alterna tra 0 e 1 (periodo {period_ms} ms, {cycles} cambi di valore). Probabilmente la stessa GA è usata per inviare e ascoltare contemporaneamente.",
      "help_url": "https://community.openhab.org/t/loops-on-knx-bus/22185"
    },
    "MULTI_TIME_MASTER": {
      "title": "Più master di tempo sullo stesso indirizzo di gruppo",
      "description": "{sources} scrivono insieme su una GA con DPT {clock_dpt}. Sorgenti di tempo duplicate causano deriva — configura un solo dispositivo come master del tempo.",
      "help_url": "https://support.knx.org/hc/en-us/articles/115001366044-Group-Addresses-Datapoint-Types"
    },
    "RECONNECT_STORM": {
      "title": "Tempesta di riconnessione dopo silenzio del bus",
      "description": "Dopo silenzio fino a {silence_until} la sorgente ha prodotto una raffica: {burst_count} telegrammi nella finestra di 30 s (normale {normal_avg}, fattore {factor}). Tipico di flooding di riconnessione dopo perdita di alimentazione.",
      "help_url": "https://github.com/home-assistant/core/issues/69328"
    },
    "SEND_CYCLE_DRIFT": {
      "title": "Ciclo di invio notevolmente abbreviato",
      "description": "Mediana Δt recente {recent_median_dt} s vs. baseline {baseline_median_dt} s — rapporto {ratio}. Ciclo di invio dimezzato; probabilmente isteresi modificata o sensore difettoso.",
      "help_url": "https://knx-blogger.de/was-ist-auf-deinem-knx-bus-los/"
    },
    "REPEAT_APPROXIMATION": {
      "title": "Sospette ripetizioni di telegramma",
      "description": "{total_repeats} telegrammi consecutivi identici con Δt < 100 ms su {period_days} giorni (~ {repeats_per_day}/giorno). Approssimazione del bit di ripetizione — confermare tramite tracer xknx (BL-D) quando disponibile.",
      "help_url": "https://knx-user-forum.de/forum/%C3%B6ffentlicher-bereich/knx-eib-forum/1611435-unbest%C3%A4tigte-telegramme-telegrammwiederholung"
    },
    "ORPHAN_GA": {
      "title": "GA nella whitelist del progetto ma silenziosa",
      "description": "Nessun telegramma osservato nel periodo {period_from} - {period_to}. Il progetto ETS contiene questa GA — rimuovila o verifica il ricevitore.",
      "help_url": "https://support.knx.org/hc/en-us/articles/115001822790-Project-Check"
    },
    "STALE_GA": {
      "title": "GA inattiva da giorni",
      "description": "Ultimo telegramma il {last_seen}, nessuna attività da {days_silent} giorni. Sensore difettoso o linea interrotta?",
      "help_url": "https://support.knx.org/hc/en-us/articles/115001822790-Project-Check"
    },
    "SEND_TO_NOWHERE": {
      "title": "Telegramma di commutazione senza eco di stato",
      "description": "Il Write alle {write_at} non ha ricevuto eco di stato entro {status_window_ms} ms sulla stessa GA. Attuatore possibilmente offline, non programmato o stato su GA separata (possibile falso positivo).",
      "help_url": "https://support.knx.org/hc/en-us/articles/360019068120-Groups-Diagnostics"
    },
    "ANALYSIS_DISABLED": {
      "title": "L'analisi del bus e disattivata",
      "description": "L'interruttore di analisi del bus e spento — il listener non registra piu telegrammi nelle tabelle raw o counter. Tutti gli altri findings sono soppressi affinche questa scheda non dia una falsa impressione di 'tutto OK'. Attiva l'interruttore nella scheda di analisi del bus KNX per riprendere la cattura dei telegrammi.",
      "help_url": ""
    }
  },
  "nl": {
    "DPT_MISMATCH": {
      "title": "Gedetecteerd datatype komt niet overeen met project-DPT",
      "description": "Auto-detector concludeerde {inferred_dpt} uit {samples} samples (zekerheid {confidence}). Project-DPT is {project_dpt}. Waarden worden mogelijk verkeerd gedecodeerd — controleer het ETS-project. Let op: actuatoren (DPT 5.001) die alleen 0% en 100% verzenden kunnen verkeerdelijk als 1.001 worden geinterpreteerd — zet de severity-override op 'info' als dat van toepassing is.",
      "help_url": "https://support.knx.org/hc/en-us/articles/115001366044-Group-Addresses-Datapoint-Types"
    },
    "VALUE_OUT_OF_RANGE": {
      "title": "Waarde buiten het toegestane DPT-bereik",
      "description": "Waarde {value} ligt buiten het toegestane bereik [{range_min}, {range_max}] voor DPT {dpt}. Waarschijnlijk verkeerd DPT of defecte sensor.",
      "help_url": "https://support.knx.org/hc/en-us/articles/115001133744-Datapoint-Type"
    },
    "MULTI_RESPONDER": {
      "title": "Meerdere actuatoren reageren op hetzelfde groepsadres",
      "description": "{count} bronnen antwoordden binnen {window_ms} ms: {responding_sources}. Waarschijnlijk meerdere actuatoren met L-flag actief — kan opzettelijk zijn bij parallelle actuatoren, anders ETS-topologie controleren.",
      "help_url": "https://knx-blogger.de/knx-flags-einfach-erklaert/"
    },
    "READ_NO_RESPONSE": {
      "title": "GroupValueRead zonder antwoord",
      "description": "Read om {read_at} heeft binnen {timeout_sec} s geen antwoord ontvangen. Ontvanger ontbreekt, is offline of L-flag is niet ingesteld.",
      "help_url": "https://support.knx.org/hc/en-us/articles/360019068120-Groups-Diagnostics"
    },
    "TOGGLE_LOOP": {
      "title": "Schakellus op DPT 1.001",
      "description": "Groepsadres wisselt cyclisch tussen 0 en 1 (periode {period_ms} ms, {cycles} waardewisselingen). Waarschijnlijk wordt dezelfde GA tegelijk verzendend en luisterend gebruikt.",
      "help_url": "https://community.openhab.org/t/loops-on-knx-bus/22185"
    },
    "MULTI_TIME_MASTER": {
      "title": "Meerdere tijdmasters op hetzelfde groepsadres",
      "description": "{sources} schrijven samen op een GA met DPT {clock_dpt}. Dubbele tijdbronnen veroorzaken drift — configureer slechts één apparaat als tijdmaster.",
      "help_url": "https://support.knx.org/hc/en-us/articles/115001366044-Group-Addresses-Datapoint-Types"
    },
    "RECONNECT_STORM": {
      "title": "Reconnect-storm na busstilte",
      "description": "Na stilte tot {silence_until} produceerde de bron een burst: {burst_count} telegrammen in het 30-s-venster (normaal {normal_avg}, factor {factor}). Typisch voor reconnect-floods na bus-spanningsverlies.",
      "help_url": "https://github.com/home-assistant/core/issues/69328"
    },
    "SEND_CYCLE_DRIFT": {
      "title": "Verzendcyclus aanzienlijk verkort",
      "description": "Recente mediaan Δt {recent_median_dt} s vs. baseline {baseline_median_dt} s — verhouding {ratio}. Verzendcyclus gehalveerd; waarschijnlijk hysterese aangepast of sensor defect.",
      "help_url": "https://knx-blogger.de/was-ist-auf-deinem-knx-bus-los/"
    },
    "REPEAT_APPROXIMATION": {
      "title": "Vermoedelijke telegram-herhalingen",
      "description": "{total_repeats} identieke opeenvolgende telegrammen met Δt < 100 ms over {period_days} dagen (~ {repeats_per_day}/dag). Benadering van de repeat-bit — bevestig via xknx-tracer (BL-D) indien beschikbaar.",
      "help_url": "https://knx-user-forum.de/forum/%C3%B6ffentlicher-bereich/knx-eib-forum/1611435-unbest%C3%A4tigte-telegramme-telegrammwiederholung"
    },
    "ORPHAN_GA": {
      "title": "GA in projectlijst maar stil",
      "description": "Geen telegrammen waargenomen in de periode {period_from} tot {period_to}. Het ETS-project bevat deze GA — verwijder hem of controleer de ontvanger.",
      "help_url": "https://support.knx.org/hc/en-us/articles/115001822790-Project-Check"
    },
    "STALE_GA": {
      "title": "GA al dagen stil",
      "description": "Laatste telegram op {last_seen}, geen activiteit sinds {days_silent} dagen. Sensor defect of lijn onderbroken?",
      "help_url": "https://support.knx.org/hc/en-us/articles/115001822790-Project-Check"
    },
    "SEND_TO_NOWHERE": {
      "title": "Schakelttelegram zonder status-echo",
      "description": "Write om {write_at} kreeg geen status-echo binnen {status_window_ms} ms op dezelfde GA. Actuator mogelijk offline, niet geprogrammeerd of status op aparte GA (mogelijk vals positief).",
      "help_url": "https://support.knx.org/hc/en-us/articles/360019068120-Groups-Diagnostics"
    },
    "ANALYSIS_DISABLED": {
      "title": "Busanalyse is uitgeschakeld",
      "description": "De busanalyse-schakelaar staat uit — de listener registreert geen telegrammen meer in de raw- of counter-tabellen. Alle andere findings zijn onderdrukt zodat dit tabblad geen valse 'alles OK'-indruk wekt. Activeer de schakelaar in het tabblad KNX-busanalyse om de telegramopname te hervatten.",
      "help_url": ""
    }
  }
};

export const SUPPORTED_LANGS: ReadonlyArray<Lang> = ["de", "en", "es", "fr", "it", "nl"];
